const SET_INPUT_VAL = "SET_INPUT_VAL"
const SET_EDIT_IND = "SET_EDIT_IND"
const DELETE_TODO = "DELETE_TODO"
const EDIT_TODO = "EDIT_TODO"
const ADD_TODO = "ADD_TODO"
const UPDATE_TODO = "UPDATE_TODO"
const CANCEL_EDIT = "CANCEL_EDIT"

export {SET_EDIT_IND, SET_INPUT_VAL, DELETE_TODO, EDIT_TODO, UPDATE_TODO, CANCEL_EDIT, ADD_TODO}